#!/usr/bin/env python3

# Dummy script as example


import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--user", help="username that should be used")
parser.add_argument("--password", help="password that should be used")
parser.add_argument("--mode", help="mode that should be used. create, reset, delete")
parser.parse_args()
